[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/media/youtube"
  to = "/.netlify/functions/youtube"
  status = 200

[[redirects]]
  from = "/api/media/substack"
  to = "/.netlify/functions/substack"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
